logging:
  level:
    org.springframework: INFO

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/dev/ivonet-applications/ivo2u-tiny/db/h2-tiny
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dbcp:
      max-active: 10
      time-between-eviction-runs-millis: 1
    dbcp2:
      max-idle: 8
      min-evictable-idle-time-millis: 10000
      min-idle: 1000
      max-wait-millis: 10000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true

flyway:
  baseline-on-migrate: true

datasource.flyway:
    url: jdbc:h2:file:~/dev/ivonet-applications/ivo2u-tiny/db/h2-tiny
    username: sa
    password:
    driver-class-name: org.h2.Driver

